// English names for the home page: day titles of course 1 and module names, in the order of the plan.
// The Russian ones live in plan-days.mjs and plan-modules.mjs; build-index.mjs uses both.

export const MODULE_NAMES_EN = {
  E1: 'Introduction and tools',
  E2: 'Syntax, types and operators',
  E3: 'Conditions and loops',
  E4: 'Functions',
  E5: 'Strings, numbers, Math and date basics',
  E6: 'Arrays, objects and JSON',
  E7: 'DOM and events',
  E8: 'Timers, promises and fetch',
  PROJECTS: 'Projects and defense',
};

export const DAY_TITLES_EN = {
  1: {
    1: 'What JavaScript is and where it runs',
    2: 'Tools: editor, page, console',
    3: 'Language overview and the first program',
    4: 'Variables: let, const, var',
    5: 'Data types and typeof',
    6: 'Arithmetic and assignment',
    7: 'Comparison and logical operators',
    8: 'Type conversion and operator precedence',
    9: 'Conditions: if, else, switch',
    10: 'Loops: for, while, do...while',
    11: 'Iterating values: for...of, for...in; try...catch',
    12: 'Functions: declaration, parameters, return',
    13: 'Arrow functions and function expressions',
    14: 'Default and rest parameters',
    15: 'Practice: splitting a task into functions (mixed day)',
    16: 'Strings and their methods',
    17: 'Numbers and first dates: Number, parseInt, Date',
    18: 'Math and random numbers',
    19: 'Arrays: creation and basic methods',
    20: 'Iterating arrays: forEach, map, filter, reduce',
    21: 'Objects: properties, methods, iteration',
    22: 'Destructuring, spread and optional chaining',
    23: 'JSON: parse and stringify',
    24: 'DOM: finding elements on the page',
    25: 'Changing the page: text, markup, attributes, classes, styles',
    26: 'Creating and removing elements',
    27: 'Events: listeners, the event object, bubbling',
    28: 'Forms: fields, submitting, input validation',
    29: 'Mini project: a to-do list',
    30: 'Timers and promises',
    31: 'fetch, async/await and localStorage',
    32: 'Mini project: a catalog with data from a server',
    33: 'Final project: idea and plan',
    34: 'Final project: implementation',
    35: 'Final project: polishing and testing',
    36: 'Project defense',
  },
};
